In [1]:
pip install numpy

In [ ]:
# NumPy is a library for the Python programming language,which works on multi-dimensional arrays and matrices

In [2]:
import numpy as np

In [3]:
my_list=[10,20,50,60,70]
my_list

[10, 20, 50, 60, 70]

In [7]:
# let's create a numpy array from the list "my_list"
x=np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [6]:
type(x)

numpy.ndarray

In [13]:
# Multi-Dimentional
matrix=np.array([[5,8],[9,13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

In [14]:
matrix.shape

(2, 2)

In [15]:
matrix.size

4

In [16]:
matrix.ndim

2

In [17]:
matrix=np.array([[[5,8],[9,13]]])
matrix

array([[[ 5,  8],
        [ 9, 13]]])

In [18]:
matrix.ndim

3

# Mini Challange
# Write a code that creates the following 2*4 numpy array

In [25]:
type(x)

numpy.ndarray

In [26]:
x.ndim

2

In [27]:
x.shape

(2, 4)

In [29]:
x.size

8

In [ ]:
x=np.array([[1,2,3,4],[5,6,7,8]])
x

# Built-In Methods And Functions

In [33]:
# "rand()" uniform distribution between 0 and 1
x=np.random.rand(15)

In [34]:
x

array([0.77029   , 0.84179176, 0.02321786, 0.65293316, 0.39510473,
       0.81342985, 0.60801618, 0.05441296, 0.40284466, 0.15383605,
       0.44988954, 0.12424829, 0.58586754, 0.26461021, 0.21482099])

In [38]:
# you can create a matrix of random number as well
x=np.random.rand(5,3) #5 rows and 3 column
x

array([[0.31764377, 0.53297579, 0.90233286],
       [0.73763286, 0.24550631, 0.85355799],
       [0.97543665, 0.64928623, 0.10555653],
       [0.25416792, 0.10794613, 0.49932197],
       [0.56109279, 0.47336484, 0.21889523]])

In [39]:
# "randn()" normal distribution between 0 amd 1
x=np.random.randn(10)
x

array([ 0.4805441 , -0.55163124,  1.08105171,  1.52607583, -0.70411689,
       -0.93633275, -0.65386696, -1.03336468,  0.40201367, -0.26236699])

In [41]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,11)
x

6

In [45]:
# "randint" can be used to generate a certain number of random integers as follows
x=np.random.randint(1,100,15)
x

array([ 2, 53, 32, 12, 80, 69, 29, 59, 11, 81, 59, 50, 69, 26, 85])

In [47]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
# Create an evenly spaced values with a step of 5
x=np.arange(0,50,5)
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [50]:
# create a diagonal of ones and zeros everwhere else
x=np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
# Array of ones
x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
# Matrices of ones
x=np.ones([5,5])
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# Array of zeros
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
# Matrices of zeros
x=np.zeros([2,3])
x

array([[0., 0., 0.],
       [0., 0., 0.]])

# Mini challange #2.

In [61]:
# Write a code that takes in a number x from the user and creates 1*20 array with random numbers ranging from 0 to x
x=np.random.randint(1,100,20)
x

array([55, 51, 25, 93, 78, 94, 16, 28, 24, 59, 34, 63, 79,  5, 85, 96, 55,
       41,  6, 70])

# 3. Shape,Length,Type,Reshape And Max/Min Values

In [63]:
# Let's define a one-dimensional array
my_list=[-30,4,50,60,29,15,22,90]
my_list
x=np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [64]:
# Get length of a numpy array
len(x)

8

In [65]:
# Get shape
x.shape

(8,)

In [66]:
# Obtain the data type
matrix.dtype

dtype('int32')

In [67]:
x.dtype   # As we check the type why does it shows us 32 alongwith int32 what does it mean?                                         Beacuse it shows us the the bit of memory e.g 32 bit and the other one is 62 bit


dtype('int32')

In [78]:
# Reshape 1D array into a matrix
z=x.reshape(4,2,1)
print(z)
z.ndim

[[[-30]
  [  4]]

 [[ 50]
  [ 60]]

 [[ 29]
  [ 15]]

 [[ 22]
  [ 90]]]


3

In [79]:
# obtain the maximum element
x.max()

90

In [80]:
# obtain the minimum element
x.min()

-30

In [82]:
#obtain the location of the max element
x.argmax()

7

In [83]:
#obtain the location of the min element
x.argmin()

0

# Mini challange #3.

In [103]:
# Write a code that creates a 4*5 array inwhich numbers range between 300 and 500 such that the 
# difference between is 10
x=np.arange(300,500,10)
x
x=x.reshape(4,5)
x

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

# Mini challange #4.

# write a code that creates a 20*20 numpy array of random values that ranges from -1000 and obtain
# the maximum,minimum and mean values


In [98]:
x=np.random.randint(-10000,1000,(20,20))
x

array([[-4782, -2107, -7398,  -494,  -805, -3058, -4986, -8272,  -515,
        -3287, -2573, -8154,   849, -6049, -2636,  -600, -9707, -5129,
         -879, -2997],
       [-4918, -5355, -2288, -6143, -2626, -7431, -6396, -5392,   331,
        -4704, -7764, -6622, -1823, -6164, -3193, -4434, -1281, -4102,
        -9387,  -154],
       [   14,   105, -5814, -6447, -1223, -6358,   763, -2410, -3831,
        -2118, -6519, -8173, -1621, -9058, -9819, -8420,   935, -6232,
        -5919, -1223],
       [-2835, -3023, -7888, -5098, -4309, -5878, -9016, -4959, -1629,
        -7434, -5336, -9338, -4704,  -160, -7168, -1685, -3140, -6923,
        -4634, -3330],
       [ -146, -3278, -6555, -8692, -7255, -6217, -4239,   733, -6840,
        -5925, -4414, -2180,  -784, -7350, -3512, -5411, -7133, -2449,
        -2141, -4502],
       [ -597, -6018, -2222,     2, -4460, -9711, -5767,   217, -9451,
        -2326,  -144, -7316, -8901, -7276, -3708, -6982,  -601, -8606,
          718, -4456],
       [-5

In [99]:
x.max()

980

In [100]:
x.min()

-9985

# 4. Methametical Operation


In [3]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y=np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
sum=x+y

In [12]:
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
s=x**2
s

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [15]:
sqrt=np.sqrt(s)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
z=np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

# 5. Slicing and Indexing

In [19]:
x=np.array([20,40,50,21,13])
x

array([20, 40, 50, 21, 13])

In [22]:
x[2]

50

In [23]:
x[0:3]

array([20, 40, 50])

In [24]:
x[0:2]=10
x

array([10, 10, 50, 21, 13])

In [25]:
matrix=np.random.randint(1,10,(5,5))

In [26]:
matrix

array([[4, 4, 3, 4, 4],
       [6, 2, 3, 5, 9],
       [7, 1, 7, 1, 8],
       [7, 8, 2, 2, 2],
       [4, 5, 6, 4, 9]])

In [27]:
matrix[2]

array([7, 1, 7, 1, 8])

In [28]:
matrix[0:4:2]

array([[4, 4, 3, 4, 4],
       [7, 1, 7, 1, 8]])

In [29]:
matrix[4][4]

9

In [30]:
mini_matrix=matrix[0:3]

In [31]:
mini_matrix

array([[4, 4, 3, 4, 4],
       [6, 2, 3, 5, 9],
       [7, 1, 7, 1, 8]])

In [40]:
mini_matrix=matrix[1:4]
mini_matrix

array([[6, 2, 3, 5, 9],
       [7, 1, 7, 1, 8],
       [7, 8, 2, 2, 2]])

In [42]:
mini_matrix=matrix[:,0:3]
mini_matrix

array([[4, 4, 3],
       [6, 2, 3],
       [7, 1, 7],
       [7, 8, 2],
       [4, 5, 6]])

In [43]:
mini_matrix=matrix[:,2:]
mini_matrix

array([[3, 4, 4],
       [3, 5, 9],
       [7, 1, 8],
       [2, 2, 2],
       [6, 4, 9]])

# Mini challange #6

In [69]:
# In the following matrix,relace the last row with -1
# Multiply the 2*2 matrix in the upper right corner by 2

x=np.random.randint(1,10,(5,5))
x

array([[5, 6, 2, 7, 1],
       [4, 7, 3, 3, 8],
       [5, 2, 4, 7, 3],
       [2, 5, 3, 1, 4],
       [3, 5, 1, 4, 5]])

In [70]:
x[-1]=-1

In [71]:
x

array([[ 5,  6,  2,  7,  1],
       [ 4,  7,  3,  3,  8],
       [ 5,  2,  4,  7,  3],
       [ 2,  5,  3,  1,  4],
       [-1, -1, -1, -1, -1]])

In [75]:
a=x[:2,3:]*2

In [76]:
a

array([[14,  2],
       [ 6, 16]])

# 6.Elements Section

In [77]:
a=np.random.randint(1,10,(5,5))
a

array([[7, 7, 3, 3, 3],
       [4, 5, 5, 5, 5],
       [1, 7, 6, 6, 4],
       [9, 6, 9, 1, 2],
       [7, 8, 8, 4, 6]])

In [78]:
b=a[a>3]
b

array([7, 7, 4, 5, 5, 5, 5, 7, 6, 6, 4, 9, 6, 9, 7, 8, 8, 4, 6])

In [79]:
c=a[a%2==0]
c

array([4, 6, 6, 4, 6, 2, 8, 8, 4, 6])

In [80]:
d=a[a%2==1]
d

array([7, 7, 3, 3, 3, 5, 5, 5, 5, 1, 7, 9, 9, 1, 7])

In [1]:
import numpy as np

In [7]:
l1=np.linspace(1,10,18).reshape(9,2)

In [8]:
l1

array([[ 1.        ,  1.52941176],
       [ 2.05882353,  2.58823529],
       [ 3.11764706,  3.64705882],
       [ 4.17647059,  4.70588235],
       [ 5.23529412,  5.76470588],
       [ 6.29411765,  6.82352941],
       [ 7.35294118,  7.88235294],
       [ 8.41176471,  8.94117647],
       [ 9.47058824, 10.        ]])

In [9]:
l1.shape

(9, 2)

In [10]:
a=np.array([3,5,8,4,7,9]).reshape(3,2)
b=np.array([4,6,9,2,4,8]).reshape(3,2)

In [11]:
a

array([[3, 5],
       [8, 4],
       [7, 9]])

In [12]:
b

array([[4, 6],
       [9, 2],
       [4, 8]])

In [13]:
 a+b

array([[ 7, 11],
       [17,  6],
       [11, 17]])

In [14]:
np.concatenate((a,b))

array([[3, 5],
       [8, 4],
       [7, 9],
       [4, 6],
       [9, 2],
       [4, 8]])

In [15]:
h=np.linspace(1,256,256).reshape(4,4,4,4)

In [16]:
h

array([[[[  1.,   2.,   3.,   4.],
         [  5.,   6.,   7.,   8.],
         [  9.,  10.,  11.,  12.],
         [ 13.,  14.,  15.,  16.]],

        [[ 17.,  18.,  19.,  20.],
         [ 21.,  22.,  23.,  24.],
         [ 25.,  26.,  27.,  28.],
         [ 29.,  30.,  31.,  32.]],

        [[ 33.,  34.,  35.,  36.],
         [ 37.,  38.,  39.,  40.],
         [ 41.,  42.,  43.,  44.],
         [ 45.,  46.,  47.,  48.]],

        [[ 49.,  50.,  51.,  52.],
         [ 53.,  54.,  55.,  56.],
         [ 57.,  58.,  59.,  60.],
         [ 61.,  62.,  63.,  64.]]],


       [[[ 65.,  66.,  67.,  68.],
         [ 69.,  70.,  71.,  72.],
         [ 73.,  74.,  75.,  76.],
         [ 77.,  78.,  79.,  80.]],

        [[ 81.,  82.,  83.,  84.],
         [ 85.,  86.,  87.,  88.],
         [ 89.,  90.,  91.,  92.],
         [ 93.,  94.,  95.,  96.]],

        [[ 97.,  98.,  99., 100.],
         [101., 102., 103., 104.],
         [105., 106., 107., 108.],
         [109., 110., 111., 112.]],

    

In [24]:
h=np.linspace(1,256,256).reshape(16,4,4)

In [25]:
h

array([[[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.],
        [ 13.,  14.,  15.,  16.]],

       [[ 17.,  18.,  19.,  20.],
        [ 21.,  22.,  23.,  24.],
        [ 25.,  26.,  27.,  28.],
        [ 29.,  30.,  31.,  32.]],

       [[ 33.,  34.,  35.,  36.],
        [ 37.,  38.,  39.,  40.],
        [ 41.,  42.,  43.,  44.],
        [ 45.,  46.,  47.,  48.]],

       [[ 49.,  50.,  51.,  52.],
        [ 53.,  54.,  55.,  56.],
        [ 57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.]],

       [[ 65.,  66.,  67.,  68.],
        [ 69.,  70.,  71.,  72.],
        [ 73.,  74.,  75.,  76.],
        [ 77.,  78.,  79.,  80.]],

       [[ 81.,  82.,  83.,  84.],
        [ 85.,  86.,  87.,  88.],
        [ 89.,  90.,  91.,  92.],
        [ 93.,  94.,  95.,  96.]],

       [[ 97.,  98.,  99., 100.],
        [101., 102., 103., 104.],
        [105., 106., 107., 108.],
        [109., 110., 111., 112.]],

       [[113., 114., 115., 116.],


In [26]:
h.ndim

3

In [27]:
h.shape

(16, 4, 4)

In [33]:
v=' happy day'
if v.find('happy'):
    print('yes')
else:
    print('no')

yes


In [31]:
-8//3

-3

In [37]:
v=' happy day'
print(v.find('happy'))

1


In [39]:
1//2

0

In [40]:
-1//2

-1

# Arithmetic operations

In [43]:
a=np.array([[3,1],[2,-1]])
b=np.array([[2,-2],[5,1]])

In [44]:
a

array([[ 3,  1],
       [ 2, -1]])

In [45]:
b

array([[ 2, -2],
       [ 5,  1]])

In [48]:
from numpy.linalg import matrix_power as mpow

In [49]:
mpow(a,3)

array([[37,  9],
       [18,  1]])

In [50]:
a*b

array([[ 6, -2],
       [10, -1]])

In [51]:
a/b

array([[ 1.5, -0.5],
       [ 0.4, -1. ]])

In [52]:
a-b

array([[ 1,  3],
       [-3, -2]])

In [53]:
a+b

array([[ 5, -1],
       [ 7,  0]])

In [54]:
a**2

array([[9, 1],
       [4, 1]], dtype=int32)

In [55]:
a%2

array([[1, 1],
       [0, 1]], dtype=int32)

In [56]:
a//2

array([[ 1,  0],
       [ 1, -1]], dtype=int32)

In [57]:
a@b

array([[11, -5],
       [-1, -5]])

In [58]:
a@a

array([[11,  2],
       [ 4,  3]])

In [60]:
arr=np.array([8,7,9,7,-3,-2])
print(arr)

[ 8  7  9  7 -3 -2]


In [61]:
arr.mean()

4.333333333333333

In [62]:
arr.sum()

26

In [65]:
m=np.sum(arr)/arr.size
print(m)

4.333333333333333


In [7]:
import numpy as np
from numpy import random

In [9]:
arr=np.array([1,2,3,4,5,6])

random.shuffle(arr)

print(arr)

[2 3 5 4 6 1]


In [10]:
arr=np.array([1,2,3,4,5])
print(random.permutation(arr))

[5 3 1 4 2]


In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr=np.array([1,2,3,4,899])

In [14]:
x=arr.view()
arr[0]=42
print(arr)
print(x)

[ 42   2   3   4 899]
[ 42   2   3   4 899]


In [15]:
x

array([ 42,   2,   3,   4, 899])

In [16]:
arr

array([ 42,   2,   3,   4, 899])

In [17]:
arr=np.array([1,2,3,4,5,6])

np.shuffle(arr)

print(arr)

AttributeError: module 'numpy' has no attribute 'shuffle'

In [23]:
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2, 3, 4]), array([5, 6, 7])]


In [24]:
arr=np.array([1,2,3,4,4,5,4])
x=np.where(arr==4)
print(x)

(array([3, 4, 6], dtype=int64),)


In [25]:
arr=np.array([1,2,3,4,4,5,4])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 4, 6], dtype=int64),)


In [29]:
arr=np.array([9,7,8,6,15,20,])
x=np.searchsorted(arr,[7,8,6])
print(x)

[4 4 0]


In [32]:
arr=np.array([9,7,5,9,8,6,15,20,])
x=np.searchsorted(arr,7,side='right')
print(x)

3


In [35]:
arr=np.round(8.1766,2)
print(arr)

8.18


In [37]:
arr=np.floor([-8.1666,6.9997])
print(arr)

[-9.  6.]


In [38]:
arr=np.ceil([-8.1666,6.9997])
print(arr)

[-8.  7.]


In [39]:
arr=np.trunc([-8.1666,6.9997])
print(arr)

[-8.  6.]


In [40]:
num1=9
num2=24
x=np.lcm(num1,num2)
print(x)

72


In [42]:
arr=np.array([8,16,24])
x=np.lcm.reduce(arr)
print(x)

48


In [43]:
arr=np.arange(1,20)
x=np.lcm.reduce(arr)
print(x)

232792560


In [44]:
arr=np.array([1,1,1,2,3,4,5,5,5,5])
x=np.unique(arr)
print(x)

[1 2 3 4 5]


In [45]:
arr1=([1,2,3,4,5])
arr2=([2,3,4,5,6])
x=np.intersect1d(arr1,arr2)
print(x)

[2 3 4 5]


In [46]:
a[1-1]=a[1]
a[1]=a[2]
a[2]=a[3]
a[3]=a[4]
a[4]=a[5]
a[5]=a[6]

NameError: name 'a' is not defined

In [49]:
a=[1,2,3]
a.append(a)
print(a)

[1, 2, 3, [...]]


In [53]:
x=['a','b','c','d']
for x[-1] in x:
    print(x[-1])

a
b
c
c


In [57]:
arr=np.array([8,16,23])
z=np.lcm.reduce(arr)
z

368

In [60]:
pip install --upgrade jupyter

Note: you may need to restart the kernel to use updated packages.


In [61]:
x=input("enter the string: ")
a=''
b=''
for i in x:
    if i.isalnum():
        a=a+i
    else:
        b=b+a[::-1]+i
        a=''
print(b+a[::-1])

enter the string: hf*876/ug*54
fh*678/gu*45


# elif 

In [ ]:
x=int(input("Enter the number: "))         
y=int(input("Enter the number: "))
z=int(input("Enter the number: "))
if x>y>z:
    print(x,"is the largest among them all")
elif y>x>z:
    print(y,"is the largest among them all")
else:
    print(z,"is the largest among them all")